#spring.application.name=springboot-websocket

spring:
  data:
    mongodb:
      username: priyanshugour
      password: Priyanshu@123
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin

server:
  port: 8088
